### ISSUE TITLE
If BMC password has changed confluent should provide a more meaningful error message

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#100]
On a single node the BMC password was changed.
Trying to query the node should fail but the error message is not user-friendly:

nodehealth  nodeb
Unexpected error

Would it be possible to make the error more meaningful to suggest you were unable to establish a connection to the BMC device ?

confluent version:
confluent_client-1.8.2-1.noarch
lenovo-confluent-0.8.1-1.noarch
confluent_server-1.8.2-1.noarch

/var/log/confluent/trace:
Jun 01 14:23:36 Traceback (most recent call last):
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 120, in sessionhdl
    connection, request, cfm, authdata, authname, skipauth)
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 187, in process_request
    send_response(hdlr, connection)
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 144, in send_response
    for rsp in responses:
  File "/opt/confluent/lib/python/confluent/plugins/hardwaremanagement/ipmi.py", line 308, in perform_requests
    configdata = cfg.get_node_attributes(nodes, _configattributes)
  File "/opt/confluent/lib/python/confluent/config/configmanager.py", line 926, in get_node_attributes
    decrypt=decrypt)
  File "/opt/confluent/lib/python/confluent/config/configmanager.py", line 498, in _decode_attribute
    retdict['value'] = decrypt_value(nodeobj[attribute]['cryptvalue'])
  File "/opt/confluent/lib/python/confluent/config/configmanager.py", line 222, in decrypt_value
    raise Exception("bad HMAC value on crypted value")
Exception: bad HMAC value on crypted value

**Comment by jjohnson42** [comment]
This has been fixed for some time...
