### ISSUE TITLE
cpio dependency missing for confluent_server

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/confluent#155]
`cpio` dependency seems to be missing for `confluent_server`.

```
[root@confluent ~]# osdeploy initialize -agusktp
[...]
TFTP service is enabled and running
Traceback (most recent call last):
  File "/opt/confluent/bin/osdeploy", line 569, in <module>
    main(sys.argv)
  File "/opt/confluent/bin/osdeploy", line 73, in main
    return initialize(cmdset)
  File "/opt/confluent/bin/osdeploy", line 413, in initialize
    packit = subprocess.Popen(['cpio', '-H', 'newc', '-o'],
  File "/usr/lib/python3.9/site-packages/eventlet/green/subprocess.py", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cpio'
```

**Comment by jjohnson42** [comment]
https://github.com/xcat2/confluent/commit/4453ba3b64bb41e6e37ae204115fdfdf6d4bc296

Will be in the next release.
