### ISSUE TITLE
nodediscover register error with 3.11

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/confluent#161]
Running `nodediscover register ...` fails with 3.11:

```
ValueError: not enough values to unpack (expected 3, got 2)
Aug 29 00:56:35 Traceback (most recent call last):
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 190, in sessionhdl
    process_request(
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 272, in process_request
    send_response(hdlr, connection)
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 224, in send_response
    for rsp in responses:
  File "/opt/confluent/lib/python/confluent/discovery/core.py", line 539, in register_remote_addrs
    for result in rpool.imap(register_remote_addr, iterate_addrs(addresses)):
  File "/usr/lib/python3.9/site-packages/eventlet/greenpool.py", line 252, in next
    val = self._next()
  File "/usr/lib/python3.9/site-packages/eventlet/greenpool.py", line 235, in _next
    return self.waiters.get().wait()
  File "/usr/lib/python3.9/site-packages/eventlet/greenthread.py", line 181, in wait
    return self._exit_event.wait()
  File "/usr/lib/python3.9/site-packages/eventlet/event.py", line 132, in wait
    current.throw(*self._exc)
  File "/usr/lib/python3.9/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/opt/confluent/lib/python/confluent/discovery/core.py", line 528, in register_remote_addr
    sd = ssdp.check_fish(('/DeviceDescription.json', nd))
  File "/opt/confluent/lib/python/confluent/discovery/protocols/ssdp.py", line 454, in check_fish
    verifycallback = lambda x: True
ValueError: not enough values to unpack (expected 3, got 2)
```

Line:

```python
url, data, targtype = urldata
```

The following commit introduced this bug: https://github.com/xcat2/confluent/commit/e9d4174ce5372e3538a539b3661d200ab04202d8

The following functions are calling `ssdp.check_fish()` the old way (without `targtype`):
```
/opt/confluent/lib/python/confluent/discovery/core.py:        sd = ssdp.check_fish(('/DeviceDescription.json', nd))
/opt/confluent/lib/python/confluent/selfservice.py:                ssdp.check_fish(('/DeviceDescription.json', rb), newport, verify_cert)
```

Quick workaround for `/opt/confluent/lib/python/confluent/discovery/protocols/ssdp.py`:

```python
    if len(urldata) == 3:
        url, data, targtype = urldata
    else:
        url, data = urldata
        targtype = 'service:redfish-bmc'
```

But you might want to implement the same `targtype` logic from`discovery/protocols/ssdp.py` to `discovery/core.py` and `selfservice.py`?

**Comment by Obihoernchen** [comment]
Fixed in https://github.com/xcat2/confluent/commit/53b9a13a515c7e09d2b888ea416f3bd3890d8c16
